// Post-generation script for Prisma Client
// Prisma 6.x generates TypeScript files, but we need JavaScript for Node.js
// This script creates proper JavaScript wrappers

const fs = require('fs');
const path = require('path');

const clientDir = path.join(__dirname, '../node_modules/.prisma/client');
const defaultJsPath = path.join(clientDir, 'default.js');

// Check if client.ts exists
const clientTsPath = path.join(clientDir, 'client.ts');
if (!fs.existsSync(clientTsPath)) {
  console.error('❌ client.ts not found. Prisma client may not be generated.');
  process.exit(1);
}

// Read the client.ts file to extract the PrismaClient export
const clientContent = fs.readFileSync(clientTsPath, 'utf8');

// Extract the PrismaClient class definition pattern
// Prisma 6.x uses: export const PrismaClient = $Class.getPrismaClientClass(__dirname)
const prismaClientMatch = clientContent.match(/export const PrismaClient = (.+?);/);
const prismaExportMatch = clientContent.match(/export \{ Prisma \}/);

if (!prismaClientMatch) {
  console.error('❌ Could not find PrismaClient export in client.ts');
  process.exit(1);
}

// Create a CommonJS default.js that properly exports PrismaClient
// We need to use a workaround since Node.js can't directly require TypeScript
// The solution is to create a JavaScript file that uses dynamic import
// or we can create a proper wrapper that uses require with proper handling

// Since ts-node-dev can handle TypeScript files when transpiling,
// we need to create a wrapper that will be processed correctly
// The issue is that @prisma/client/default.js expects a .js file at .prisma/client/default

// Solution: Create a JavaScript file that uses require.cache and module.exports
// to properly export from the TypeScript files, but in a way that works with ts-node

const defaultJsContent = `// Auto-generated by postgenerate.js
// This file allows @prisma/client to find the Prisma Client
// Prisma 6.x generates TypeScript files, so we create this JavaScript bridge

// Since we're using ts-node-dev, we can require TypeScript files
// But we need to do it in a way that works with the module system
const path = require('path');
const fs = require('fs');

// Get the client directory
const clientDir = __dirname;

// The actual Prisma Client is in client.ts
// With ts-node-dev, we can require it, but we need to handle it properly
// Try to load the client module
let PrismaClient;
let Prisma;

try {
  // Since ts-node-dev processes .ts files, we need to use a different approach
  // We'll use the runtime library directly
  const runtime = require('@prisma/client/runtime/library');
  const enums = require('./enums.ts');
  const internalClass = require('./internal/class.ts');
  const internalNamespace = require('./internal/prismaNamespace.ts');
  
  // Recreate the PrismaClient export using the same pattern as client.ts
  PrismaClient = internalClass.getPrismaClientClass(__dirname);
  Prisma = internalNamespace;
  
  // Also export enums
  const $Enums = enums;
  
  module.exports = {
    PrismaClient,
    Prisma,
    $Enums,
    ...enums
  };
} catch (error) {
  // Fallback: Try to use eval or other method
  // This is a workaround for the TypeScript import issue
  console.error('Error loading Prisma Client:', error.message);
  
  // Last resort: Create a proxy that will work at runtime
  // The actual Prisma Client will be loaded when needed
  module.exports = {
    PrismaClient: class PrismaClientProxy {
      constructor(options) {
        // This will be handled by the actual client at runtime
        throw new Error('Prisma Client not properly initialized. Please check your Prisma setup.');
      }
    }
  };
}
`;

fs.writeFileSync(defaultJsPath, defaultJsContent);
console.log('✅ Created default.js for Prisma Client');

// Also create/update index.js if it doesn't exist or needs updating
const indexJsPath = path.join(clientDir, 'index.js');
if (!fs.existsSync(indexJsPath)) {
  // Create index.js that exports from default.js
  const indexJsContent = `// Auto-generated index.js
module.exports = require('./default.js');
`;
  fs.writeFileSync(indexJsPath, indexJsContent);
  console.log('✅ Created index.js');
}
