// simulator/community/sendCommunityWebhook.js
import { httpClient, resolveUrl } from '../httpClient.js';
import dotenv from 'dotenv';

dotenv.config();

/**
 * Send a dummy community/forum-style message to the ingestion service.
 */
async function sendCommunityWebhook({
  platform = 'discourse',
  threadId = 'thread-789',
  postId = 'post-001',
  title = 'Dummy community topic from simulator',
  content = 'This is a dummy forum-style message generated by the simulator.',
  userId = 'community-user-789',
  subject = 'Community topic from simulator',
  customerName = 'Community Simulator User',
  customerEmail,
  priority = 'medium',
  tags = [
    { name: 'simulator', confidence: 1 },
    { name: 'community', confidence: 0.9 },
  ],
  metadata = {},
} = {}) {
  const url = resolveUrl('COMMUNITY_INGEST_URL', '/api/queries');

  const payload = {
    channel: 'community',
    subject,
    message: content,
    customerName,
    ...(customerEmail ? { customerEmail } : {}),
    priority,
    tags,
    metadata,
    simulatedAt: new Date().toISOString(),
    source: 'audience-simulator',
    original: {
      platform,
      threadId,
      postId,
      userId,
      title,
    },
  };

  const response = await httpClient.post(url, payload);
  console.log('[COMMUNITY WEBHOOK SENT]', {
    status: response.status,
    url,
  });

  return response.data;
}

async function run() {
  try {
    await sendCommunityWebhook();
  } catch (error) {
    console.error('[COMMUNITY SIMULATOR ERROR]', error.message);
    process.exitCode = 1;
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  // Executed directly via `node simulator/community/sendCommunityWebhook.js`
  void run();
}

export { sendCommunityWebhook };
