// simulator/email/sendEmail.js
import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

/**
 * Send a dummy email to your email ingestion address using SMTP.
 */
async function sendEmail({
  to,
  from,
  subject,
  text,
  html,
} = {}) {
  const {
    SMTP_HOST,
    SMTP_PORT,
    SMTP_USER,
    SMTP_PASS,
    SMTP_SECURE,
    EMAIL_INGESTION_TO,
    EMAIL_FROM,
  } = process.env;

  if (!SMTP_HOST || !SMTP_PORT) {
    throw new Error('SMTP_HOST and SMTP_PORT must be set in your environment.');
  }

  if (!EMAIL_INGESTION_TO) {
    throw new Error('EMAIL_INGESTION_TO must be set to your ingestion email address.');
  }

  const transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: Number(SMTP_PORT),
    secure: SMTP_SECURE === 'true', // true for 465, false for others
    auth: SMTP_USER && SMTP_PASS
      ? {
          user: SMTP_USER,
          pass: SMTP_PASS,
        }
      : undefined,
  });

  const mailOptions = {
    from: from || EMAIL_FROM || 'simulator@example.com',
    to: to || EMAIL_INGESTION_TO,
    subject: subject || 'Unified Audience Simulator - Dummy Email',
    text:
      text ||
      'This is a dummy email generated by the Unified Audience Message Simulator.',
    html:
      html ||
      '<p>This is a <strong>dummy email</strong> generated by the Unified Audience Message Simulator.</p>',
  };

  const info = await transporter.sendMail(mailOptions);
  console.log('[EMAIL SENT]', {
    messageId: info.messageId,
    response: info.response,
  });

  return info;
}

async function run() {
  try {
    await sendEmail();
  } catch (error) {
    console.error('[EMAIL SIMULATOR ERROR]', error.message);
    process.exitCode = 1;
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  // Executed directly via `node simulator/email/sendEmail.js`
  void run();
}

export { sendEmail };
